package fr.cda.controller;

import fr.cda.Config;
import fr.cda.model.*;
import fr.cda.model.dao.OrderDAO;
import fr.cda.model.dao.ProductDAO;
import fr.cda.util.CryptHelper;
import fr.cda.util.FTPSender;
import fr.cda.util.SerializerHelper;

import java.nio.file.Path;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * This class handle the interaction others want to ask at the Database
 */
public class AppController
{
    private final ProductDAO productDAO;
    private final OrderDAO orderDAO;

    //region CTOR

    /**
     * @param database The database linked to us
     */
    public AppController(final Database database)
    {
        productDAO = new ProductDAO(database);
        orderDAO = new OrderDAO(database);
    }
    //endregion CTOR

    //region PUBLIC_METHODS
    /**
     * Call this to generate a crypted backup of the content of the linked {@link Database}
     * The backup is then sent on a remote server
     * @return An {@link OperationResult} able to tell if the operation succeeded via {@link OperationResult#HasSucceeded()}
     */
    public OperationResult<Void> GenerateBackUp()
    {
        //Generate the file from the current state of the Database
        OperationResult<Void> saveProdRes = SaveProductToFile(Config.OUTPUT_FILE_PATH, Config.OUTPUT_PRODUCT_FILE_NAME);
        if (!saveProdRes.HasSucceeded())
            return OperationResult.FAILURE(saveProdRes.getMessage());

        OperationResult<Void> saveOrderRes = SaveOrderToFile(Config.OUTPUT_FILE_PATH, Config.OUTPUT_ORDER_FILE_NAME);
        if (!saveOrderRes.HasSucceeded())
            return OperationResult.FAILURE(saveOrderRes.getMessage());


        //Encrypt the files
        Path completePath = Path.of(Config.OUTPUT_FILE_PATH, Config.OUTPUT_PRODUCT_FILE_NAME);
        boolean cryptResult = CryptHelper.EncryptFile(completePath.toString(), Config.OUTPUT_CRYPTED_FILE_PATH, Config.OUTPUT_CRYPTED_PRODUCT_FILE_NAME,
                Config.TINK_CRYPTED_KEY);
        if (!cryptResult)
            return OperationResult.FAILURE("ERROR : An issue occurred during encryption of file : " + completePath.toString());

        completePath = Path.of(Config.OUTPUT_FILE_PATH, Config.OUTPUT_ORDER_FILE_NAME);
        cryptResult = CryptHelper.EncryptFile(completePath.toString(), Config.OUTPUT_CRYPTED_FILE_PATH, Config.OUTPUT_CRYPTED_ORDER_FILE_NAME,
                Config.TINK_CRYPTED_KEY);
        if (!cryptResult)
            return OperationResult.FAILURE("ERROR : An issue occurred during encryption of file : " + completePath.toString());


        final Path productEncryptedPath = Path.of(Config.OUTPUT_CRYPTED_FILE_PATH, Config.OUTPUT_CRYPTED_PRODUCT_FILE_NAME);
        final Path orderEncryptedPath = Path.of(Config.OUTPUT_CRYPTED_FILE_PATH, Config.OUTPUT_CRYPTED_ORDER_FILE_NAME);


        //Send them to remote server via FTP
        OperationResult<Void> ftpResult = FTPSender.SendData(new String[]{productEncryptedPath.toString(), orderEncryptedPath.toString()},
                Config.FTP_SERVER_URL, Config.FTP_SERVER_USERNAME, Config.FTP_SERVER_PASSWORD,
                Config.FTP_SERVER_PATH_TO_SEND,21);

        if (!ftpResult.HasSucceeded())
        {
            return OperationResult.FAILURE(ftpResult.getMessage());
        }
        return OperationResult.SUCCESS("SUCCESS : Backup correctly generated and sent to the distant server.");
    }

    /**
     * Generate a String ready to be displayed, containing all the profit generated by the currently delivered {@link Order}
     * @return An {@link OperationResult} able to tell if the operation succeeded via {@link OperationResult#HasSucceeded()}
     * and containing, in case of success, a String ready to be displayed with all the relatives information
     */
    public OperationResult<String> GenerateProfitFile()
    {
        OperationResult<Order[]> ordersOperation = orderDAO.ReadAllData();
        if (!ordersOperation.HasSucceeded())
        {
            return OperationResult.FAILURE(ordersOperation.getMessage());
        }

        List<Order> orderDelivered = Arrays.stream(ordersOperation.getData())
                                             .filter(Order::isDelivered)
                                             .toList();

        ArrayList<Float> orderProfit = new ArrayList<>();
        orderProfit.ensureCapacity(orderDelivered.size());

        StringBuilder builder = new StringBuilder();
        for (Order order : orderDelivered)
        {
            builder.append(CollectOrderData(order, orderProfit));
        }

        float totalProfit = 0f;
        for (Float value : orderProfit)
        {
            totalProfit += value;
        }

        builder.append("ENTIRE SUM : ").append(String.format("%.2f", totalProfit)).append("€\n");
        return OperationResult.SUCCESS(builder.toString(), "SUCCESS : Completed computation of profit made");
    }


    /**
     * Used to call {@link OrderDAO#MakeAllDeliveries()} on the linked {@link OrderDAO}
     * @return An {@link OperationResult} able to tell if the operation succeeded via {@link OperationResult#HasSucceeded()}
     * and, in case of success, containing the array of {@link Order} that we cannot fulfill, with an explanation set on each one of them
     */
    public OperationResult<Order[]> MakeAllDeliveries()
    {
        return orderDAO.MakeAllDeliveries();
    }
    //region CRUD_operation

    //region ORDER_Crud
    /**
     * Action to call if you want to create a new {@link Order} in the {@link Database}
     * @param data The new {@link Order} to insert generated via {@link Order#GenerateOrderDTO(String, LocalDate, List)}
     * @return An {@link OperationResult} able to tell if the operation succeeded via {@link OperationResult#HasSucceeded()}
     * and, in case of success, containing the {@link ID} generated during the insertion for this object
     */
    public OperationResult<ID> CreateNewOrder(final Order data)
    {
        return orderDAO.CreateNewData(data);
    }

    /**
     * Action to call if you want to get the data of a {@link Order} from the {@link Database}
     * @param id The {@link ID} of the targeted {@link Order}
     * @return An {@link OperationResult} able to tell if the operation succeeded via {@link OperationResult#HasSucceeded()}
     */
    public OperationResult<Order> ReadOrder(final ID id)
    {
        return orderDAO.ReadData(id);
    }

    /**
     * Action to call if you want to get the data of all {@link Order} from the {@link Database}
     * @return An {@link OperationResult} able to tell if the operation succeeded via {@link OperationResult#HasSucceeded()}
     * and containing an array of copied {@link Order}
     */
    public OperationResult<Order[]> ReadAllOrder()
    {
        return orderDAO.ReadAllData();
    }

    /**
     * Action to call if you want to update the data of an {@link Order} in the {@link Database}
     * @param order An {@link Order} containing the updated data AND a valid {@link ID}
     * @return An {@link OperationResult} able to tell if the operation succeeded via {@link OperationResult#HasSucceeded()}
     */
    public OperationResult<Void> UpdateOrder(final Order order)
    {
        return orderDAO.UpdateData(order);
    }

    /**
     * Action to call if you want to delete an {@link Order} in the {@link Database}
     * @param id The {@link ID} of the targeted {@link Order}
     * @return An {@link OperationResult} able to tell if the operation succeeded via {@link OperationResult#HasSucceeded()}
     */
    public OperationResult<Void> DeleteOrder(final ID id)
    {
        return orderDAO.DeleteData(id);
    }
    //endregion ORDER_Crud

    //region PRODUCT_Crud
    /**
     * Action to call if you want to create a new {@link Product} in the {@link Database}
     * @param data The new {@link Product} to insert generated via {@link Product#GenerateProductDTO(String, Category, float, int)}
     * @return An {@link OperationResult} able to tell if the operation succeeded via {@link OperationResult#HasSucceeded()}
     * and, in case of success, containing the {@link ID} generated during the insertion for this object
     */
    public OperationResult<ID> CreateNewProduct(final Product data)
    {
        return productDAO.CreateNewData(data);
    }

    /**
     * Action to call if you want to create a new {@link Category} for the {@link Product} in the {@link Database}
     * @param category The {@link Category} you want to insert
     * @return An {@link OperationResult} able to tell if the operation succeeded via {@link OperationResult#HasSucceeded()}
     */
    public OperationResult<Void> CreateNewProductCategory(final Category category)
    {
        return productDAO.CreateNewProductCategory(category);
    }

    /**
     * Action to call if you want to get the data of a {@link Product} from the {@link Database}
     * @param id The {@link ID} of the targeted {@link Product}
     * @return An {@link OperationResult} able to tell if the operation succeeded via {@link OperationResult#HasSucceeded()}
     */
    public OperationResult<Product> ReadProduct(final ID id)
    {
        return productDAO.ReadData(id);
    }

    /**
     * Action to call if you want to get the data of all {@link Product} from the {@link Database}
     * @return An {@link OperationResult} able to tell if the operation succeeded via {@link OperationResult#HasSucceeded()}
     * and containing an array of copied {@link Product}
     */
    public OperationResult<Product[]> ReadAllProduct()
    {
        return productDAO.ReadAllData();
    }

    /**
     * Retrieve all the categories already inserted in the database
     * @return An {@link OperationResult} able to tell if the operation succeeded via {@link OperationResult#HasSucceeded()}
     * and containing, in case of success, an array of {@link Category} corresponding to all the categories in the database
     */
    public OperationResult<Category[]> ReadAllProductCategories()
    {
        return productDAO.ReadAllProductCategories();
    }

    /**
     * Action to call if you want to update the data of a {@link Product} in the {@link Database}
     * @param product A {@link Product} containing the updated data AND a valid {@link ID}
     * @return An {@link OperationResult} able to tell if the operation succeeded via {@link OperationResult#HasSucceeded()}
     */
    public OperationResult<Void> UpdateProduct(final Product product)
    {
        return productDAO.UpdateData(product);
    }

    /**
     * Action to call if you want to delete a {@link Product} in the {@link Database}
     * @param id The {@link ID} of the targeted {@link Product}
     * @return An {@link OperationResult} able to tell if the operation succeeded via {@link OperationResult#HasSucceeded()}
     */
    public OperationResult<Void> DeleteProduct(final ID id)
    {
        return productDAO.DeleteData(id);
    }
    //endregion PRODUCT_Crud

    //endregion CRUD_operation

    //endregion PUBLIC_METHODS

    //region PRIVATE_METHODS
    /**
     * Call to retrieve and format all the data concerning the {@link Product} inside the linked {@link Database}
     * The file is in CSV format
     * @param filePath The path where you want to save your file
     * @param fileName The name of the generated file
     * @return An OperationResult able to tell if the operation succeeded via {@link OperationResult#HasSucceeded()}
     */
    private OperationResult<Void> SaveProductToFile(final String filePath, final String fileName)
    {
        OperationResult<Product[]> readResult = productDAO.ReadAllData();
        if (!readResult.HasSucceeded())
            return OperationResult.FAILURE(readResult.getMessage());

        final String productAsCSV = GenerateAllCSVProductData(readResult.getData());
        boolean serialisationRes = SerializerHelper.SerializeToFile(productAsCSV, filePath, fileName);

        final String COMPLETE_PATH = filePath + "\\" + fileName;
        return serialisationRes ? OperationResult.SUCCESS("SUCCESS : All products has been serialised at path : "
                                                                  + COMPLETE_PATH)
                       : OperationResult.FAILURE("FAIL : An issue occurred while saving product at path "
                                                         + COMPLETE_PATH);
    }

    /**
     * Call to retrieve and format all the data concerning the {@link Order} inside the linked {@link Database}
     * The file is in CSV format
     * @param filePath The path where you want to save your file
     * @param fileName The name of the generated file
     * @return An OperationResult able to tell if the operation succeeded via {@link OperationResult#HasSucceeded()}
     */
    private OperationResult<Void> SaveOrderToFile(final String filePath, final String fileName)
    {
        OperationResult<Order[]> readResult = orderDAO.ReadAllData();
        if (!readResult.HasSucceeded())
            return OperationResult.FAILURE(readResult.getMessage());

        final String orderAsCSV = GenerateAllCSVOrderData(readResult.getData());
        boolean serialisationRes = SerializerHelper.SerializeToFile(orderAsCSV, filePath, fileName);

        final String COMPLETE_PATH = filePath + "\\" + fileName;
        return serialisationRes ? OperationResult.SUCCESS("SUCCESS : All products has been serialised at path : "
                                                                  + COMPLETE_PATH)
                       : OperationResult.FAILURE("FAIL : An issue occurred while saving product at path "
                                                         + COMPLETE_PATH);
    }

    /**
     * Generate one CSV formatted String for all {@link Product} in parameter
     * @param data The {@link Product} you want to use to generate the String
     * @return A CSV formatted String containing all the data concatenated corresponding to each Product passed in parameter
     */
    private String GenerateAllCSVProductData(final Product[] data)
    {
        final StringBuilder builder = new StringBuilder();
        final char NEW_LINE = '\n';

        for (Product product : data)
        {
            builder.append(GenerateCSVProductData(product));
            builder.append(NEW_LINE);
        }
        return builder.toString();
    }

    /**
     * Generate a CSV formatted String based on a {@link Product}
     * @param product The targeted object
     * @return A String formatted in CSV
     */
    private String GenerateCSVProductData(final Product product)
    {
        //FORMAT : ID (Category-Number) ; Name ; Price ; Quantity
        //LIVRE-1;Les Miserables de Victor Hugo;8.50;6

        final char CSV_SEPARATOR = ';';

        final StringBuilder builder = new StringBuilder();
        builder.append(product.getId().id()).append(CSV_SEPARATOR)
                .append(product.getName()).append(CSV_SEPARATOR)
                .append(String.format("%.2f", product.getPrice())).append(CSV_SEPARATOR)
                .append(product.getStoredQuantity());

        return builder.toString();
    }


    /**
     * Generate one CSV formatted String for all {@link Order} in parameter
     * @param data The {@link Order} you want to use to generate the String
     * @return A CSV formatted String containing all the data concatenated corresponding to each Order passed in parameter
     */
    private String GenerateAllCSVOrderData(Order[] data)
    {
        final StringBuilder builder = new StringBuilder();
        final char NEW_LINE = '\n';

        for (Order order : data)
        {
            builder.append(GenerateCSVOrderData(order));
            builder.append(NEW_LINE);
        }
        return builder.toString();
    }

    /**
     * Generate a CSV formatted String based on an {@link Order}
     * @param order The targeted object
     * @return A String formatted in CSV
     */
    private String GenerateCSVOrderData(final Order order)
    {
        //FORMAT : ID ; CreationDate ; ClientName ; ProductRef (ID=Quantity)...
        //1;21/09/2022;Macron Brigitte;LIVRE-1=1;LIVRE-2=2;...

        final StringBuilder builder = new StringBuilder();
        final char CSV_SEPARATOR = ';';

        final DateTimeFormatter DATE_FORMATTER = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        final String FORMATTED_DATE = order.getCreationDate().format(DATE_FORMATTER);

        builder.append(order.getId().id()).append(CSV_SEPARATOR)
                .append(FORMATTED_DATE).append(CSV_SEPARATOR)
                .append(order.getClientName()).append(CSV_SEPARATOR);

        for (int i = 0 ; i < order.getOrderedProduct().size() ; ++i)
        {
            final OrderDetail detail = order.getOrderedProduct().get(i);

            builder.append(detail.productID().id()).append("=")
                    .append(detail.productQuantity());

            if (i !=  order.getOrderedProduct().size() - 1)
            {
                builder.append(CSV_SEPARATOR);
            }
        }
        return builder.toString();
    }


    /**
     * Generate a String already formatted to display the detail of the profit made by an Order
     * @param order The order you want to generate the string from
     * @param orderProfit We put inside this list the sum of the profit made by the order
     * @return A String ready to display the profit generated by the order
     */
    private String CollectOrderData(final Order order, ArrayList<Float> orderProfit)
    {
        StringBuilder builder = new StringBuilder();
        float profitOnOrder = 0f;

        builder.append("ORDER NUMBER : ").append(order.getId().id()).append("\n");

        for (OrderDetail detail : order.getOrderedProduct())
        {
            OperationResult<Product> readResTemp = productDAO.ReadData(detail.productID());
            if (!readResTemp.HasSucceeded())
                continue;

            final Product product = readResTemp.getData();
            final float profitOnDetail = detail.productQuantity() * readResTemp.getData().getPrice();

            builder.append("\t").append(product.getName())
                    .append("  ").append(detail.productQuantity())
                    .append("  ").append(String.format("%.2f", product.getPrice()))
                    .append("€").append("\n");


            profitOnOrder += profitOnDetail;
        }
        builder.append("\n").append("Sum : ").append(String.format("%.2f", profitOnOrder)).append("€\n")
                .append("=======================\n\n");

        orderProfit.add(profitOnOrder);
        return builder.toString();
    }
    //endregion PRIVATE_METHODS
}
