!ifndef MODEL__PUML
!define MODEL__PUML


!include dao/DAOPackage.puml


!include ../util/UtilPackage.puml
!include ../controller/ControllerPackage.puml


package model
{
    class BackApp
    {
        - database : Database
        - appController : AppController
        - hasAnActiveConnection : boolean

        + BackApp(database)

        + HasAnActiveConnection() : boolean
        + RequestNewConnection() : OperationResult<AppController>
    }

    record Category
    {
        + Category(categoryName : String)
    }

    class Database
    {
        - productMap : Map<Category, ProductCategoryMap>>
        - orderMap : Hashmap<ID, Order>
        - orderIDGenerator : DataIdGenerator

        + CreateNewProduct(data : Product) : OperationResult<ID>
        + CreateNewProductCategory(category : Category) OperationResult<Void>
        + ReadProduct(id : ID) : OperationResult<Product>
        + ReadAllProduct() : OperationResult<Product[]>
        + ReadAllProductCategories() : OperationResult<Category[]>
        + UpdateProduct(data : Product) OperationResult<Void>
        + DeleteProduct(id : ID) OperationResult<Void>

        + CreateNewOrder(data : Order) : OperationResult<ID>
        + ReadOrder(id : ID) : OperationResult<Order>
        + ReadAllOrder() : OperationResult<Order[]>
        + UpdateOrder(data : Order) OperationResult<Void>
        + DeleteOrder(id : ID) OperationResult<Void>

        + MakeAllDeliveries() : OperationResult<Order[]>

        - Init()
        - InitProduct()
        - InitOrder()
        - ExtractFromFileAndInsertProduct(line : String)
        - ExtractFromFileAndInsertOrder(line : String)

        - ReadProductInternal(id : ID) : OperationResult<Product>
        - SplitProductID(productId : ID) : OperationResult<String[]>
        - ExtractProductCategoryFromID(readedID) : OperationResult<Category>
        - CheckIfProductCategoryExist(category) : OperationResult<Void>
        - UpdateProductIdGenerator(productId, category)

        - ReadOrderInternal(id : ID) : OperationResult<Order>
        - CheckIfOrderIsDoable(order) : boolean
        - FulfillOrder(order)
        - SetNonDoableOrderReason(order)
        - ExtractOrderDetail(orderContent : ArrayList<String>, orderID) : List<OrderDetail>
        - UpdateOrderIdGenerator(orderID : ID)
    }

    class DataIdGenerator
    {
        - currentId : long

        + GetNextId() : long
        + GetNextIdAsString() : String
        + TryUpdateCurrentId(value : long)
    }

    record ID
    {
        + ID(id : String)
    }

    class OperationResult <T>
    {
        - data : T
        - message : final String
        - success : final boolean

        - OperationResult(data, message, success)

        + {static} Success(message : String, data : T) : OperationResult<T>
        + {static} Success(message : String) : OperationResult<T>
        + {static} Failure(message : String) : OperationResult<T>

        + HasSucceeded() : boolean
        + GetMessage() : String
        + GetData() : T
    }

    class Order
    {
        - id : ID
        - creationDate : LocalDate
        - clientName : String
        - orderedProduct : List<OrderDetail>
        - isDelivered : boolean
        - nonDeliveredExplanation : String

        + Order(id : ID, creationDate, clientName, orderedProduct)
        + Order(other : Order)
        - Order(clientName, creationDate, orderedProduct)

        + {static} GenerateOrderDTO(clientName, creationDate, orderedProduct) : Order
        + UpdateToNonDeliveredStatus(explanation : String)
        + UpdateToDeliveredStatus()
    }

    record OrderDetail
    {
        + OrderDetail(productID : ID, productQuantity : int)
    }

    class Product
    {
        - id : ID
        - name : String
        - category : Category

        - price : float
        - storedQuantity : int

        + Product(id, name, category, price, storedQuantity)
        + Product(other : Product)
        - Product(name, category, price, storedQuantity)
        + {static} GenerateProductDTO(name, category, price, storedQuantity) : Product
    }

    class ProductCategoryMap
    {
        - categoryIDGenerator : DataIdGenerator
        - productMap : Map<ID, Product>

        + getProductMap() : Map<ID, Product>
        + GetNextCategoryIdAsString() : String
        + TryUpdateCategoryID(value : long)
    }

    note right of Database::productMap
        First map use category as key
        Next map use complete id
    end note


    Order "0-n" --* Database

    OrderDetail "1-n" --* Order

    Product "0-n" --* ProductCategoryMap

    ID "1" --* Order
    ID "1" --* Product
    ID "1" --* OrderDetail

    Category "1" --* Product
    Category "1" --* ProductCategoryMap

    DataIdGenerator "1" --* Database
    DataIdGenerator "1" --* ProductCategoryMap

    ProductCategoryMap "n" --* Database

    Database "1" --o BackApp
    Database --> OperationResult
}

model.Database --> util.SerializerHelper
controller.AppController "1" --* model.BackApp

!endif