@startuml
'https://plantuml.com/class-diagram

!define MODEL_FOCUS

!include ../Common.puml
!include ModelPackage.puml

remove util.CryptHelper
remove util.DeliverMailHelper

remove controller.GUIController
remove controller.DatabaseConnectionException
remove controller.DatabaseConnectionEvent

remove view

remove async

remove event

@enduml