@startuml
'https://plantuml.com/class-diagram

skinparam classAttributeIconSize 0

package greta.fr
{
    class View
    class Controller
    class Model
    class ModelDTO

    class Product{
    - id : String
    - name : String
    - price : float
    - storedQuantity : int
    }

    class Site{
    - allOrder : ArrayList<Order>
    - storedProduct : ArrayList<Product>

    + ListAllProducts() : String
    + ListAllOrder() : String
    + ListOrder(final int id) : String
    }

    class Order{
    - id : int
    - creationDate : LocalDate
    - clientName : String
    - orderedProduct : ArrayList<Product>
    - isDelivered : boolean
    - nonDeliveredExplanation : String
    }

    package "Task"
    {
        class DeliverMailTask
        class CryptDataTask
    }

    package "Util"
    {
        class SerializerHelper
        class DeliverMailHelper
        class CryptHelper
        class LoggerHelper
    }
}

@enduml