!ifndef UTIL__PUML
!define UTIL_PUML

package util
{
    abstract CryptHelper
    {
        - {static} static()

        + {static} DecryptFile(fileToDecrypt: String, keyToUse : String)
        + {static} EncryptFile(fileToCrypt: String, cryptedPathLocation : String, cryptedFileName : String, keyToUse : String)
        + {static} GenerateKey()
    }

    abstract FTPSender
    {
        + {static} SendData(fileToSend : String[], serverUrl, serverUsername, serverPassword, remoteServerPath, port : int) : OperationResult<Void>
        - {static} CreateDirToDistantRepo(ftpClient : FTPClient, dirPath : String)
    }

   abstract LoggerHelper
    {
        + {static} log : log4j::Logger
    }

    abstract MailMessenger
    {
        + {static} SendMail(targetMail, targetName, senderMail, senderName, subject, content, attachmentPath : Path[]) : OperationResult<Void>
    }

    abstract SerializerHelper
    {
        + {static} ReadFileAsByte(filePath : String) : byte[]
        + {static} ReadFile(filePath : String) : String[]
        + {static} SerializeToFile(content : byte[], path : String, fileName : String) : boolean
        + {static} SerializeToFile(content : String, path : String, fileName : String) : boolean
        + {static} FileExist (filePath : String) : boolean
        + {static} HideBreakLineForCSV(line : String) : String
        + {static} ShowBreakLineFromCSV(line : String) : String
        + {static} EnsureOrCreatePath(filePath : String) : boolean
    }

    abstract SwingHelper
    {
        + {static} SetSameSize(components : JComponent[])
        + {static} DetermineMaxSize(components : JComponent[]) : Dimension
        + {static} AddComponentToPanelWithStruts(targetPanel : JPanel, components : JComponent[], horizontalStrut : int, verticalStrut : int)
        + {static} CreateNonEditableTextArea() : JTextArea
    }

    note right of LoggerHelper
        Can be used by everyone
    end note
}

!endif