@startuml
'https://plantuml.com/class-diagram

!include Common.puml

package model
{
    class BackApp
    class Database
    class DAO
    class Product
    class Order
}

package controller
{
    class AppController
    class GUIController
}

package view
{
    class FrontApp
    class HomeFrame
    class AnyDialogView
}

package util
{
    class CryptHelper
    class FTPSender
    class LoggerHelper
    class MailMessenger
    class SerializerHelper
    class SwingHelper
}

circle files

note top of GUIController : Thread all his operations
note right of Database : Keep data in memory while app is running

Database "1" --* BackApp
AppController "1" --* BackApp

Order "n" --* "1" Database
Product "n" --* "1" Database
Database --> files

DAO --> Database : Send Crud operation
DAO "n" --* "1" AppController

GUIController <--> AppController : exchange operation and result

GUIController --* FrontApp : send result

AnyDialogView "n" --* "1" HomeFrame
HomeFrame "1" --* FrontApp
HomeFrame --> controller.GUIController


@enduml