@startuml
'https://plantuml.com/class-diagram

skinparam classAttributeIconSize 0

package greta.fr
{
    !include util/UtilPackage.puml
    !include task/TaskPackage.puml
    !include swing/SwingPackage.puml
    !include site/SitePackage.puml
    !include model/modelPackage.puml
    !include controller/ControllerPackage.puml
    !include view/ViewPackage.puml
    !include dao/DAOPackage.puml
}

@enduml