@startuml
'https://plantuml.com/class-diagram


!include ../../Common.puml
!include DAOPackage.puml

remove model.DataIdGenerator
remove model.ProductCategoryMap
remove model.BackApp


remove util

remove controller.GUIController
remove controller.DatabaseConnectionEvent
remove controller.DatabaseOperationEndedEvent
remove controller.DatabaseConnectionException

remove event
remove view
remove async

@enduml