!ifndef DAO__PUML
!define DAO__PUML

!include ../ModelPackage.puml

package model.dao
{
    abstract DAO<T>
    {
        # Database

        + DAO(database)

        + {abstract} CreateNewData(data : T) : OperationResult<ID>
        + {abstract} ReadData(id : ID) : OperationResult<T>
        + {abstract} ReadAllData() : OperationResult<T[]>
        + {abstract} UpdateData(data : T) : OperationResult<Void>
        + {abstract} DeleteData(id : ID) : OperationResult<Void>

        + SaveDataToFile(path : String) : OperationResult<Void>
    }

    class OrderDAO <Order> <<final>>

    class ProductDAO <Product> <<final>>
    {
        + CreateNewProductCategory(category : Category) :
    }

    OrderDAO --|> DAO
    ProductDAO --|> DAO
}

model.Database "1" ..o model.dao.DAO

!endif