!ifndef DAO__PUML
!define DAO__PUML

package "DAO"
{
    OrderDAO --|> DAOModel
    ProductDAO --|> DAOModel

    abstract DAOModel<T>
    {
        # linkedSite : Site

        + {abstract} Create(id : String) : T
        + {abstract} Read(id : String) : T
    }

    class OrderDAO <Order> <<final>>
    {

    }

    class ProductDAO <Product> <<final>>
    {

    }
}

!endif