package fr.cda.model;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Contain a map of <{@link ID}, {@link Product}> and a {@link DataIdGenerator} used to keep
 * track an internal counter dedicated to a {@link Category}
 */
public class ProductCategoryMap
{
    private final DataIdGenerator categoryIDGenerator;
    private final Map<ID, Product> productMap;

    public ProductCategoryMap()
    {
        categoryIDGenerator = new DataIdGenerator();
        productMap = new LinkedHashMap<>();
    }

    public Map<ID, Product> getProductMap()
    {
        return productMap;
    }

    /**
     * Used to retrieve the next {@link ID} generated by the internal {@link DataIdGenerator}
     * @return The new generated {@link ID} in String format
     */
    public String GetNextCategoryIdAsString()
    {
        return categoryIDGenerator.GetNextIdAsString();
    }

    /**
     * Use to update the internal {@link DataIdGenerator} value, using internally {@link DataIdGenerator#TryUpdateCurrentId(long)}
     * @param value A value you want to be certain to be lower than the next generated {@link ID}
     */
    public void TryUpdateCategoryID(final long value)
    {
        categoryIDGenerator.TryUpdateCurrentId(value);
    }
}
