!ifndef ASYNC__PACKAGE
!define ASYNC__PACKAGE

package async
{
    class AsyncQueue
    {
        - executor : ExecutorService

        + AsyncQueue(threadName : String)
        + SubmitAsyncOperation <T> ( operation : Supplier<T>, onOperationDone : Consumer<T>)
        + Shutdown()
    }
}

!endif