@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0

!include ../view/ViewPackage.puml
!include ../model/ModelPackage.puml

package Site
{
    Site "n" *-- "1" SiteConfig
    Site *-- "1" MainApp

    Site "n" *-- "1" Product
    Site "n" *-- "1" Order


    class SiteConfig
    {
        - siteName : String
        - int appWidth
        - int appHeight

        + {static} DEFAULT : SiteConfig
    }

    class Site{
        - allOrder : Hashmap<String, Order>
        - allProduct : Hashmap<String, Product>

        + ListAllProducts() : String
        + ListAllOrder() : String
        + ListOrder(final int id) : String

        - LoadConfig()
        - LoadCustomConfig() : boolean
        - LoadDefaultConfig()
        - LaunchApp()
        }
}

@enduml