!ifndef SITE__PUML
!define SITE__PUML

!include ../view/ViewPackage.puml
!include ../model/ModelPackage.puml
!include ../util/UtilPackage.puml
!include ../dao/DaoPackage.puml

package Site
{
    Site "n" *-- "1" SiteConfig
    Site *-- "1" MainApp

    Site "1" *-- "n" Product
    Site "1" *-- "n" Order

    Site *-- "1" OrderDAO
    Site *-- "1" ProductDAO


    Site --> SerializerHelper
    Site <-- DAO.DAO

    class SiteConfig
    {
        - siteName : String
        - int appWidth
        - int appHeight

        + {static} DEFAULT : SiteConfig
    }

    class Site
    {
        - allOrder : Hashmap<String, Order>
        - allProduct : Hashmap<String, Product>

        + ListAllProducts() : String
        + ListAllOrder() : String
        + ListOrder(final int id) : String

        - LoadConfig()
        - LoadCustomConfig() : boolean
        - LoadDefaultConfig()
        - LaunchApp()
    }
}

!endif