!ifndef VIEW__PUML
!define VIEW__PUML

!include swing/SwingPackage.puml
!include ../controller/ControllerPackage.puml

package view
{
    class FrontApp
    {
        - allOrder : Hashmap<String, Order>
        - allProduct : Hashmap<String, Product>

        - homeViewConfig : SwingViewConfig

        + FrontApp()
        - LaunchApp()
        + EstablishConnection(backApp : BackApp)

        - LoadConfig()
        - LoadCustomConfig() : boolean
        - LoadDefaultConfig()

        - CreateHomeView()
        - ConnectToDatabase(remoteController : AppController) : OperationResult<Void>
        - GetDataFromDatabase()

        # ListAllProducts() : String
        # ListAllOrder() : String
        # ListOrder(final int id) : String
    }


    class HomeFrame <<final>>
    {
        - JTextArea infoArea
        - JTextArea productDetailArea

        - buttonShowStorage : JButton
        - buttonShowOrder : JButton
        - buttonShowSpecificOrder : JButton
        - buttonMakeDeliveries : JButton
        - buttonComputeProfit : JButton
        - buttonSendMailData : JButton
        - buttonGenerateBackUp : JButton

        - {static} PANEL_BORDER_SIZE : int {final}

        # Init()

        - JPanel CreateCenterPanel()
        - JPanel CreateInfoArea()
        - JPanel CreateListAndDescriptionPanel()
        - JPanel CreateButtonPanel()
    }


    FrontApp "1" ..> HomeFrame

    HomeFrame "1" --* FrontApp
    HomeFrame --|> swing.SwingFrame
    HomeFrame --> swing.SwingHelper
}

controller.GUIController "1" --* view.FrontApp


!endif