!ifndef VIEW__PUML
!define VIEW__PUML

!include ../swing/SwingPackage.puml
!include ../util/UtilPackage.puml

View --> SwingHelper

package "View"
{
    Frame <|-- MainApp

    class MainApp <<final>>
    {
        - JTextArea infoArea
        - JTextArea productDetailArea

        - buttonShowStorage : JButton
        - buttonShowOrder : JButton
        - buttonShowSpecificOrder : JButton
        - buttonMakeDeliveries : JButton
        - buttonComputeProfit : JButton
        - buttonSendMailData : JButton
        - buttonGenerateBackUp : JButton

        - {static} PANEL_BORDER_SIZE : int {final}

        # Init()

        - JPanel CreateCenterPanel()
        - JPanel CreateInfoArea()
        - JPanel CreateListAndDescriptionPanel()
        - JPanel CreateButtonPanel()
    }
}

!endif