@startuml
'https://plantuml.com/class-diagram


!include ../Common.puml
!include ViewPackage.puml

remove model

remove util.SerializerHelper
remove util.FTPSender
remove util.CryptHelper
remove util.MailMessenger

remove controller.AppController

@enduml