!ifndef SWING__PUML
!define SWING__PUML

package "Swing"
{
    ISwingInterface <|.. AbstractSwingInterface
    AbstractSwingInterface <|-- Frame
    AbstractSwingInterface <|-- Dialog
    AbstractSwingInterface "0-n" *-- "1" SwingInterfaceConfig

    interface ISwingInterface
    {
        + Display()
        + Hide()
    }

    abstract AbstractSwingInterface
    {
        + AbstractSwingInterface(config : SwingInterfaceConfig, autoShow : boolean)
        # {abstract} Init()
        - LoadConfig()
    }

    note left of AbstractSwingInterface::Init
        Called from the ctor
        Will serve to create the
        interface with Swing components
    end note

    note left of AbstractSwingInterface::LoadConfig
                Called from the ctor
    end note

    class SwingInterfaceConfig
    {
        - title : String
        - width : int
        - height : int

        + SwingInterfaceConfig(title, width, height)
        + {static} DEFAULT : SiteConfig
    }

    abstract Dialog
    {
        # dialog JDialog

        # Dialog(frameOwner : JFrame, config, autoShow : boolean)
    }

    abstract Frame
    {
        # frame : JFrame

        #Frame(config : SwingInterfaceConfig, autoShow : boolean)
    }
}


!endif