!ifndef SWING__PUML
!define SWING__PUML

package "Swing"
{
    ISwingInterface <|.. Frame
    ISwingInterface <|.. Dialog

    abstract Dialog
    {
        # dialog JDialog

        # Dialog(title : String, frameOwner : JFrame, width : int, height : int, autoShow : boolean)
        # {abstract} Init()
    }

    abstract Frame
    {
        # frame : JFrame

        #Frame(title : String, width : int, height : int, autoShow : boolean)
        # {abstract} Init()
    }

    interface ISwingInterface
    {
        + Display()
        + Hide()
    }
}

!endif