@startuml
'https://plantuml.com/class-diagram

!include ../Common.puml
!include ControllerPackage.puml


remove model.idGenerator
remove model.Database

remove util.SwingHelper
remove util.SerializerHelper

remove async

@enduml