!ifndef CONTROLLER__PUML
!define CONTROLLER__PUML

!include ../model/ModelPackage.puml
!include ../view/swing/async/SwingAsyncPackage.puml
!include ../event/EventPackage.puml

package controller
{
    class AppController
    {
        + AppController(database : Database)

        + SaveProductToFile(filePath : String) : OperationResult<String>
        + SaveOrderToFile(filePath : String) : OperationResult<String>

        + CreateNewProduct(data : Product) : OperationResult<String>
        + CreateNewProductCategory(category : Category) OperationResult<Void>
        + ReadProduct(id : String) : OperationResult<Product>
        + ReadAllProduct() : OperationResult<ArrayList<Product>>
        + UpdateProduct(data : Product) OperationResult<Void>
        + DeleteProduct(id : String) OperationResult<Void>

        + CreateNewOrder(data : Order) : OperationResult<String>
        + ReadOrder(id : String) : OperationResult<Order>
        + ReadAllOrder() : OperationResult<ArrayList<Product>>
        + UpdateOrder(data : Order) OperationResult<Void>
        + DeleteOrder(id : String) OperationResult<Void>

        + MakeAllDeliveries() : OperationResult<Order[]>

        + SendDeliveredOrderByMail() : OperationResult<Void>
        + SaveBackViaFTP() : OperationResult<Void>
    }

    class GUIController
    {
        + eventBus : EventBus
        - appController : AppController

        + ConnectToBackApp(backApp : BackApp) : OperationResult<Void>
        + IsConnected() : OperationResult<Void>


        + SaveProductToFile(filePath : String, callback : Consumer<OperationResult<String>>)
        + SaveOrderToFile(filePath : String, callback : Consumer<OperationResult<String>>)

        + CreateNewProduct(data : Product, callback : Consumer<OperationResult<ID>>)
        + CreateNewProductCategory(category : Category, callback : Consumer<OperationResult<Void>>)
        + ReadProduct(id : ID, callback : Consumer<OperationResult<Product>>)
        + ReadAllProduct(callback : Consumer<OperationResult<Product[]>>)
        + UpdateProduct(data : Product, callback : Consumer<OperationResult<Void>>)
        + DeleteProduct(id : ID, callback : Consumer<OperationResult<Void>>)

        + CreateNewOrder(data : Order, callback : Consumer<OperationResult<ID>>)
        + ReadOrder(id : ID, callback : Consumer<OperationResult<Order>>)
        + ReadAllOrder(callback : Consumer<OperationResult<Order[]>>)
        + UpdateOrder(data : Order, callback : Consumer<OperationResult<Void>>)
        + DeleteOrder(id : ID, callback : Consumer<OperationResult<Void>>)
        + MakeDeliveries(callback : Consumer<OperationResult<Order[]>>)

        + SendDeliveredOrderByMail(callback : Consumer<OperationResult<Void>>)
        + SaveBackViaFTP(callback : Consumer<OperationResult<Void>>)
    }

    exception DatabaseConnectionException

    record DatabaseConnectionEvent
    {
        + DatabaseConnectionEvent(message : String, isConnected : boolean)
    }

    note right of GUIController
        Use his own thread to treat demands
        from FrontApp while keeping order
    end note


    AppController "1" --o GUIController
}

model.dao.ProductDAO "1" --* controller.AppController
model.dao.OrderDAO "1" --* controller.AppController

controller.AppController --> util.DeliverMailHelper
controller.AppController --> util.CryptHelper

view.swing.async.SwingAsyncQueue "1" --* controller.GUIController

event.EventBus "1" --* controller.GUIController

!endif