!ifndef CONTROLLER__PUML
!define CONTROLLER__PUML

!include ../model/ModelPackage.puml
!include ../view/swing/async/SwingAsyncPackage.puml
!include ../event/EventPackage.puml

package controller
{
    class AppController
    {
        - productDAO : ProductDAO
        - orderDAO : orderDAO

        + AppController(database : Database)

        + GenerateBackUp() : OperationResult<Void>
        + GenerateProfitFile() : OperationResult<String>
        + MakeAllDeliveries() : OperationResult<Order[]>

        + CreateNewOrder(data : Order) : OperationResult<String>
        + ReadOrder(id : String) : OperationResult<Order>
        + ReadAllOrder() : OperationResult<ArrayList<Product>>
        + UpdateOrder(data : Order) OperationResult<Void>
        + DeleteOrder(id : String) OperationResult<Void>

        + CreateNewProduct(data : Product) : OperationResult<String>
        + CreateNewProductCategory(category : Category) OperationResult<Void>
        + ReadProduct(id : String) : OperationResult<Product>
        + ReadAllProduct() : OperationResult<ArrayList<Product>>
        + ReadAllProductCategories() : OperationResult<Category[]>
        + UpdateProduct(data : Product) OperationResult<Void>
        + DeleteProduct(id : String) OperationResult<Void>

        - SaveProductToFile(filePath : String, fileName : String) : OperationResult<Void>
        - SaveOrderToFile(filePath : String, fileName : String) : OperationResult<Void>

        - GenerateAllCSVProductData(data : Product[]) : String
        - GenerateCSVProductData(data : Product) : String
        - GenerateAllCSVOrderData(data : Order[]) : String
        - GenerateCSVOrderData(data : Order) : String
        - CollectOrderData(order : Order, orderProfit : ArrayList<Float>) : String
    }

    class GUIController
    {
        - appController : AppController
        - swingAsyncQueue : SwingAsyncQueue

        + eventBus : EventBus

        + CreateNewProduct(data : Product, callback : Consumer<OperationResult<ID>>)
        + CreateNewProductCategory(category : Category, callback : Consumer<OperationResult<Void>>)
        + ReadProduct(id : ID, callback : Consumer<OperationResult<Product>>)
        + ReadAllProduct(callback : Consumer<OperationResult<Product[]>>)
        + ReadAllProductCategory(callback : Consumer<OperationResult<Category[]>>)
        + UpdateProduct(data : Product, callback : Consumer<OperationResult<Void>>)
        + DeleteProduct(id : ID, callback : Consumer<OperationResult<Void>>)

        + CreateNewOrder(data : Order, callback : Consumer<OperationResult<ID>>)
        + ReadOrder(id : ID, callback : Consumer<OperationResult<Order>>)
        + ReadAllOrder(callback : Consumer<OperationResult<Order[]>>)
        + UpdateOrder(data : Order, callback : Consumer<OperationResult<Void>>)
        + DeleteOrder(id : ID, callback : Consumer<OperationResult<Void>>)

        + ConnectToBackApp(backApp : BackApp) : OperationResult<Void>
        + IsConnected() : OperationResult<Void>


        + SaveProductToFile(filePath : String, callback : Consumer<OperationResult<String>>)
        + SaveOrderToFile(filePath : String, callback : Consumer<OperationResult<String>>)
        + MakeAllDeliveries(callback : Consumer<OperationResult<Order[]>>)

        + QueryProfitMade(callback : Consumer<OperationResult<String>>)
        + SendOrderReviewByMail(callback : Consumer<OperationResult<Void>>)
        + SaveBackViaFTP(callback : Consumer<OperationResult<Void>>)

        - VerifyConnection()
        - DatabaseOperationCallbackWrapper(callBack : Consumer<OperationResult<T>>) : Consumer<OperationResult<T>>
    }

    exception DatabaseConnectionException

    record DatabaseConnectionEvent
    {
        + DatabaseConnectionEvent(message : String, isConnected : boolean)
    }

    record DatabaseOperationEndedEvent
    {
        + DatabaseOperationEndedEvent(message : String)
    }

    note right of GUIController
        Use his own thread to treat demands
        from FrontApp while keeping order
    end note


    AppController "1" --o GUIController

    GUIController --> DatabaseConnectionEvent
    GUIController --> DatabaseOperationEndedEvent
    GUIController --> DatabaseConnectionException
}

model.dao.ProductDAO "1" --* controller.AppController
model.dao.OrderDAO "1" --* controller.AppController

controller.AppController --> util.CryptHelper
controller.AppController --> util.FTPSender
controller.AppController --> util.SerializerHelper
controller.AppController --> model.OperationResult
controller.GUIController --> util.MailMessenger

view.swing.async.SwingAsyncQueue "1" --* controller.GUIController

event.EventBus "1" --* controller.GUIController

!endif